### PR TITLE
replace tag symbols

### PR DESCRIPTION
**Pull request by whooooop**
You can write html code in the tag code
&lt;pre>
&lt;code>
&lt;div>test&lt;/div>
&lt;/code>
&lt;/pre>

### CODE REVIEW

**Comment by bebraw** [comment]
It probably would make sense to use something like https://www.npmjs.com/package/ent here. That would give us a general solution. What do you think?

**Comment by bebraw** [comment]
@serzz1990 I implemented proper tests for the loader. If you have time, it would be cool if you could try to re-implement this idea now. It should be far easier to pull it off correctly now.

**Comment by whooooop** [comment]
I think you need to create an option entHTML,
Otherwise, it is necessary to add
.replace (/ & quot; / g, ' "')
.replace (/ & lt; / g, '<')
.replace (/ & gt; / g, '>');
for that would not break the already formatted HTML

**Comment by bebraw** [comment]
@serzz1990 Can you design a test case? I don't mind implementing if you can do that.

**Pull request closed without merging**
