### PR TITLE
Add raw and lang query options

### PR DESCRIPTION
**Pull request by davidtheclark**
This adds `raw` and `lang` query options. If the user provides a value to `raw`, then the module's content is treated as a raw string, run through highlight.js with the language auto-detected, and returned. If the user wants to specify a language instead of using highlight.js's auto-detection, that's what `lang` is for. If `raw` is not passed, the loader should work exactly the same as it has been working so far.

I've tried this out on my own project and it seems to work well.

What do you think? Is this a good addition to the loader?

### CODE REVIEW

**Comment by bebraw** [comment]
> What do you think? Is this a good addition to the loader?

Yeah, looks good.

Can you update the README with basic docs? Add yourself to contributors as well.

I'll merge and release after that.

Thanks!

**Comment by davidtheclark** [comment]
Just added documentation.

**Comment by davidtheclark** [comment]
Fixed that typo, thanks.

**Comment by bebraw** [comment]
Just published `0.5.0`. Thanks!

**Pull request merged**
